### ISSUE TITLE
"Cannot read property 'Trips'..."

### ISSUE THREAD

**Issue by nickdc1964** [polastre/united#10] opened 2017-12-09 16:37 UTC
Tried it on both a Mac and a PC running Windows 10 - same error on both. Any ideas?
![screen shot 2017-12-09 at 10 34 37 am](https://user-images.githubusercontent.com/34400579/33797414-f6fdc5bc-dccc-11e7-968e-a6088cac4ea7.png)

**Comment by polastre** [comment] 2017-12-09 18:30
Dupe of #7

**Closed by polastre** 2017-12-09 18:30 UTC
