### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by pxia** [polastre/united#9] opened 2017-11-27 19:37 UTC
```
/Users/pxia/work/united/united.js:78
  var flights = data.data['Trips'][0]['Flights']
                         ^

TypeError: Cannot read property 'Trips' of undefined
    at parseResults (/Users/pxia/work/united/united.js:78:26)
    at Request._callback (/Users/pxia/work/united/united.js:107:18)
    at Request.self.callback (/Users/pxia/work/united/node_modules/request/request.js:198:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/pxia/work/united/node_modules/request/request.js:1082:10)
    at emitOne (events.js:120:20)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/Users/pxia/work/united/node_modules/request/request.js:1009:12)
    at emitNone (events.js:110:20)
```

`data` is a HTML error message from united website:
> You don't have permission to access "http://www.united.com/ual/en/us/flight-search/book-a-flight/flightshopping/getflightresults/rev" on this server.

**Comment by polastre** [comment] 2017-11-27 19:45
Dupe of #7

**Closed by polastre** 2017-11-27 19:45 UTC
